name: test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.9]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run CI test
        run: make ci-test POETRY_VENV_CREATE=false POETRY_VENV_IN_PROJECT=false
        env:
          SORACOM_AUTH_KEY: ${{ secrets.SORACOM_AUTH_KEY }}
          SORACOM_AUTH_KEY_ID: ${{ secrets.SORACOM_AUTH_KEY_ID }}
